{% set name = "gspread-pandas" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4db9e901ac3c91535b2b7226015799ffce0a24fdde77a53251d83128af83c48b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
  run:
    - python >={{ python_min }}
    - gspread >=5.0.0,<6
    - pandas >=0.20.0
    - decorator
    - google-auth
    - google-auth-oauthlib

test:
  imports:
    - gspread_pandas
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://github.com/aiguofer/gspread-pandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A package to easily open an instance of a Google spreadsheet and interact with worksheets through Pandas DataFrames.
  doc_url: https://gspread-pandas.readthedocs.io/en/latest
  dev_url: https://github.com/aiguofer/gspread-pandas

extra:
  recipe-maintainers:
    - mariusvniekerk
